---
- name: Configure kubernetes cluster
  hosts: localhost
  vars:
    cluster_name: stage-schedule
    cluster_zone: us-central1-b
    schedule_app_repo: "https://github.com/BlueTeam2/class-schedule-k8s.git"

  tasks:
    - name: Get environment variables
      shell: "env"
      register: env_output

    - debug:
        var: env_output.stdout_lines
        
    - name: Prints two lines of messages, but only if there is an environment value set
      ansible.builtin.debug:
        msg:
        - "Provisioning based on GCP_SERVICE_ACCOUNT_FILE which is: {{ lookup('ansible.builtin.env', 'GCP_SERVICE_ACCOUNT_FILE') }}"
        
    - name: Generate kubeconfig to use kubeclt
      ansible.builtin.shell: 
        cmd: |
          gcloud auth activate-service-account --key-file="$GCP_SERVICE_ACCOUNT_FILE" --project "$GCP_PROJECT"
    
    - name: Generate kubeconfig to use kubeclt
      ansible.builtin.shell: 
        cmd: |
          gcloud container clusters get-credentials "{{ cluster_name }}" --zone "{{ cluster_zone }}" --project "$GCP_PROJECT"


    - name: Add external-secrets repository
      kubernetes.core.helm_repository:
        repo_name: external-secrets
        repo_url: "https://charts.external-secrets.io"

    - name: Deploy external-secrets chart
      kubernetes.core.helm:
        chart_ref: external-secrets/external-secrets
        create_namespace: true
        release_namespace: external-secrets
        release_name: external-secrets
        set_values:
          - value: installCRDs=true

    - name: Git clone stable repo on HEAD
      ansible.builtin.git:
        repo: "{{ schedule_app_repo }}"
        dest: /tmp/helm_class_schedule

    - name: Deploy backend
      kubernetes.core.helm:
        release_name: backend
        chart_ref: /tmp/helm_class_schedule/backend
        release_namespace: schedule-app
        create_namespace: true
        dependency_update: true
        set_values:
          - value: environmentType=stage

    - name: Deploy frontend
      kubernetes.core.helm:
        release_name: frontend
        chart_ref: /tmp/helm_class_schedule/frontend
        release_namespace: schedule-app
        create_namespace: true
